version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    docker:
      - image: circleci/node:18.18.0
    steps: # steps 키 추가
      - checkout # 코드 체크아웃
      - run:
          name: Install dependencies
          command: npm ci # 의존성 설치
      - run:
          name: Run Cypress tests
          command: npm run dev # Cypress 테스트 실행
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: "npm run dev"
